language: ruby
rvm:
- 2.1.0
deploy:
  provider: heroku
  api_key:
    secure: RFKbSgJTT4JAOiO+KFc+CcXGXARN03YB5VWQ1x60lBCIPzON37Lryh49/E+qX3+oDUFtvwGq4xueb8ZtzNG/crmATmYE+Ir/gM0luAScAGSpdQ/VVJdHoGtVeHXKHSBTnd+YfMQDdmryNybSE0OYkYd1Yop2R+3H7+qFT7y4tV4=
  app:
    master: app-ideas-prod
    development: app-ideas-staging
  on:
    repo: tktl-app-ideas/appideas
  run: "rake db:migrate" 
