language: ruby
rvm:
- 2.1.0
deploy:
  provider: heroku
  api_key:
    secure: doEcOhCcxUiRop/XxuTJl2YxMzVzfWL2UjJ3FN/nUqLeoRLOUTaC9tfKZ1HvMloE4DXnMrGvRtJ4o1kJ9Gd09fuHR6qWdGqgvkYzI3zcC5YzG9R6H9HaxWmqBjd3EHUNMB+wcbtSYZpuXYmv9/kvHsyHwEk923yDT95G9ihkBfg=
  app:
    master: app-ideas-prod
    development: app-ideas-staging
  on:
    repo: tktl-app-ideas/appideas
  run: "rake db:migrate" 
